DROP TABLE IF EXISTS cyclistSeq5s;
CREATE TABLE cyclistSeq5s(
	eventNum int,
	Device	smallint,
	Trip	smallint,
	`Time`	int,
	TargetId	tinyint,
	ObstacleId	tinyint,
	`Range`	real,
	Rangerate	real,
	Transversal	real,
	TargetType	tinyint,
	`Status`	tinyint,
	CIPV	tinyint,
	GpsValidWsu	tinyint,
	GpsTimeWsu	bigint,
	LatitudeWsu	float,
	LongitudeWsu	float,
	AltitudeWsu	real,
	GpsHeadingWsu	real,
	GpsSpeedWsu	real,
	HdopWsu	real,
	PdopWsu	real,
	FixQualityWsu	tinyint,
	GpsCoastingWsu	tinyint,
	ValidCanWsu	tinyint,
	YawRateWsu	real,
	SpeedWsu	real,
	TurnSngRWsu	tinyint,
	TurnSngLWsu	tinyint,
	BrakeAbsTcsWsu	tinyint,
	AxWsu	real,
	PrndlWsu	tinyint,
	VsaActiveWsu	tinyint,
	HeadlampWsu	tinyint,
	WiperWsu	tinyint,
	ThrottleWsu	real,
	SteerWsu	real);
    
    call cyclistSeq5sBefAft();
    